--Create table (create DB first):  

USE [WebScraper]
GO

/****** Object:  Table [dbo].[Searches]    Script Date: 04/03/2024 23:46:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Searches](
	[Id] [uniqueidentifier] NOT NULL,
	[Url] [nvarchar](1000) NULL,
	[Keywords] [nvarchar](500) NULL,
	[Position] [nvarchar](1000) NULL,
	[Date] [datetime2](7) NOT NULL,
	[Occurrences] [int] NOT NULL,
 CONSTRAINT [PK_SearchResults] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--Create Database:

USE [master]
GO

/****** Object:  Database [WebScrape]    Script Date: 04/03/2024 23:47:07 ******/
CREATE DATABASE [WebScrape]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebScrape', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WebScrape.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebScrape_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WebScrape_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebScrape].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebScrape] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebScrape] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebScrape] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebScrape] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebScrape] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebScrape] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebScrape] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebScrape] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebScrape] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebScrape] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebScrape] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebScrape] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebScrape] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebScrape] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebScrape] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebScrape] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebScrape] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebScrape] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebScrape] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebScrape] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebScrape] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebScrape] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebScrape] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WebScrape] SET  MULTI_USER 
GO

ALTER DATABASE [WebScrape] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebScrape] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebScrape] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebScrape] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebScrape] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebScrape] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WebScrape] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WebScrape] SET  READ_WRITE 
GO






